import type { PluginManifest, ThemePaletteConfig } from "@hyacine/contract";

/**
 * 规范化 CSS 变量名，确保包含 `--` 前缀
 */
export function normalizeCssVarName(key: string): string {
  const trimmed = key.trim();
  if (trimmed.startsWith("--")) {
    return trimmed;
  }
  return `--${trimmed}`;
}

/**
 * 将键值对象序列化为 CSS 规则体
 */
function formatCssDeclarations(vars?: Record<string, string>): string {
  if (!vars || Object.keys(vars).length === 0) return "";
  return Object.entries(vars)
    .map(([key, value]) => `  ${normalizeCssVarName(key)}: ${value};`)
    .join("\n");
}

/**
 * 合并多个插件中声明的调色板与主题样式（按插件声明顺序，后声明的覆盖先声明的）
 */
export function mergeThemePalettes(manifests: PluginManifest[]): ThemePaletteConfig {
  const mergedRoot: Record<string, string> = {};
  const mergedLight: Record<string, string> = {};
  const mergedDark: Record<string, string> = {};
  const mergedCssFiles: string[] = [];
  const customCssList: string[] = [];

  for (const manifest of manifests) {
    const palette = manifest.theme?.palette;
    if (!palette) continue;

    if (palette.root) {
      Object.assign(mergedRoot, palette.root);
    }
    if (palette.light) {
      Object.assign(mergedLight, palette.light);
    }
    if (palette.dark) {
      Object.assign(mergedDark, palette.dark);
    }
    if (palette.cssFiles && Array.isArray(palette.cssFiles)) {
      for (const file of palette.cssFiles) {
        if (file && !mergedCssFiles.includes(file)) {
          mergedCssFiles.push(file);
        }
      }
    }
    if (palette.customCss && palette.customCss.trim()) {
      customCssList.push(palette.customCss.trim());
    }
  }

  return {
    root: Object.keys(mergedRoot).length > 0 ? mergedRoot : undefined,
    light: Object.keys(mergedLight).length > 0 ? mergedLight : undefined,
    dark: Object.keys(mergedDark).length > 0 ? mergedDark : undefined,
    cssFiles: mergedCssFiles.length > 0 ? mergedCssFiles : undefined,
    customCss: customCssList.length > 0 ? customCssList.join("\n\n") : undefined,
  };
}

/**
 * 将 ThemePaletteConfig 转换为可在页面全局注入的 CSS 样式代码
 */
export function generatePaletteCSS(palette?: ThemePaletteConfig): string {
  if (!palette) {
    return "/* Auto-generated by @hyacine/plugin-core (Empty theme palette) */\n";
  }

  const sections: string[] = ["/* Auto-generated by @hyacine/plugin-core */"];

  // 1. @import 外部样式文件
  if (palette.cssFiles && palette.cssFiles.length > 0) {
    const imports = palette.cssFiles
      .map((file) => `@import ${JSON.stringify(file.replace(/\\/g, "/"))};`)
      .join("\n");
    sections.push(imports);
  }

  // 2. :root 全局变量
  if (palette.root && Object.keys(palette.root).length > 0) {
    sections.push(`:root {\n${formatCssDeclarations(palette.root)}\n}`);
  }

  // 3. 浅色模式变量
  if (palette.light && Object.keys(palette.light).length > 0) {
    sections.push(
      `:root,\n[data-theme="light"],\n.light,\nhtml.light {\n${formatCssDeclarations(palette.light)}\n}`,
    );
  }

  // 4. 深色模式变量
  if (palette.dark && Object.keys(palette.dark).length > 0) {
    sections.push(
      `[data-theme="dark"],\n.dark,\nhtml.dark {\n${formatCssDeclarations(palette.dark)}\n}`,
    );
  }

  // 5. 自定义内联 CSS
  if (palette.customCss && palette.customCss.trim()) {
    sections.push(`/* Custom Theme Styles */\n${palette.customCss.trim()}`);
  }

  if (sections.length === 1) {
    return "/* Auto-generated by @hyacine/plugin-core (Empty theme palette) */\n";
  }

  return `${sections.join("\n\n")}\n`;
}
