import { fileURLToPath } from "node:url";
import { pascalCase } from "es-toolkit";
import type {
  CustomElementEntry,
  InjectEntry,
  RuntimeOnlyEntry,
  SSREntry,
} from "@hyacine/contract";

export function normalizeImportPath(path: string): string {
  if (path.startsWith("file://")) {
    try {
      return fileURLToPath(path).replace(/\\/g, "/");
    } catch {
      return path;
    }
  }
  return path.replace(/\\/g, "/");
}

export function safeComponentName(name: string, index: number): string {
  const pc = pascalCase(name);
  if (/^[A-Z][A-Za-z0-9]*$/.test(pc)) {
    return `${pc}${index}`;
  }
  return `HyacineSlotComp${index}`;
}

function safeHydrationInstruction(hydration: SSREntry["clientHydrationInstruction"]): string {
  if (
    hydration === "load" ||
    hydration === "idle" ||
    hydration === "visible" ||
    hydration === "media"
  ) {
    return `client:${hydration}`;
  }
  return "";
}

/**
 * 将 props 对象序列化为 JSX 属性字符串
 */
function serializeProps(props?: Record<string, unknown>): string {
  if (!props || Object.keys(props).length === 0) return "";

  return Object.entries(props)
    .map(([key, value]) => {
      if (!/^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key)) return "";
      if (typeof value === "string") {
        const escaped = value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
        return ` ${key}="${escaped}"`;
      } else if (typeof value === "number" || typeof value === "boolean") {
        return ` ${key}={${value}}`;
      } else if (value === null || value === undefined) {
        return "";
      } else {
        return ` ${key}={${JSON.stringify(value)}}`;
      }
    })
    .join("");
}

/**
 * 生成插槽专用的 Astro 虚拟组件源码
 */
export function generateSlotAstroComponent(slotName: string, entries: InjectEntry[]): string {
  if (entries.length === 0) {
    return `---
// @ts-nocheck
// Auto-generated by @hyacine/plugin-astro (Slot: ${slotName})
---
<!-- hyacine slot: ${slotName} (empty) -->
<slot />
`;
  }

  const ssrEntries = entries.filter(
    (e): e is SSREntry | CustomElementEntry => e.type === "ssr" || e.type === "custom-element",
  );

  const imports: string[] = [];
  const renderTags: string[] = [];

  ssrEntries.forEach((entry, idx) => {
    const compName = safeComponentName(entry.name || `slot_${slotName}`, idx);
    const importPath = JSON.stringify(normalizeImportPath(entry.path));
    imports.push(`import ${compName} from ${importPath};`);

    if (entry.type === "ssr") {
      const hydration = safeHydrationInstruction(entry.clientHydrationInstruction);
      const propsStr = serializeProps(entry.props);
      const hydrationAttr = hydration ? ` ${hydration}` : "";
      renderTags.push(
        `<${compName}${hydrationAttr} hyacineArticle={Astro.props?.context?.data ?? Astro.props?.context ?? Astro.props?.hyacineArticle ?? null}${propsStr} {...Astro.props?.extraProps} />`,
      );
    } else {
      // custom-element
      renderTags.push(`<${compName} />`);
    }
  });

  const importsBlock = imports.length > 0 ? `\n${imports.join("\n")}` : "";
  const renderedContent =
    renderTags.length > 0
      ? `  ${renderTags.join("\n  ")}\n  <slot />`
      : `  <slot />`;

  return `---
// @ts-nocheck
// Auto-generated by @hyacine/plugin-astro (Slot: ${slotName})${importsBlock}
---
<div class="hyacine-slot hyacine-slot-${slotName}" data-hyacine-slot="${slotName}">
${renderedContent}
</div>
`;
}

/**
 * 生成聚合客户端 Runtime 插件初始化代码
 */
export function generateRuntimeModuleCode(entries: RuntimeOnlyEntry[]): string {
  if (entries.length === 0) {
    return `// Auto-generated by @hyacine/plugin-astro (No runtime plugins registered)
export function init() {}
export default { init };
`;
  }

  const imports: string[] = [];
  const calls: string[] = [];

  entries.forEach((entry, idx) => {
    const fnName = `initPlugin${idx}`;
    const importPath = JSON.stringify(normalizeImportPath(entry.path));
    imports.push(`import { init as ${fnName} } from ${importPath};`);

    const optionsStr = entry.options ? JSON.stringify(entry.options) : "{}";
    calls.push(`
  try {
    if (typeof ${fnName} === "function") {
      ${fnName}(${optionsStr});
    }
  } catch (err) {
    console.error("[hyacine] Failed to init runtime plugin \\"${entry.name}\\":", err);
  }`);
  });

  return `// @ts-nocheck
// Auto-generated by @hyacine/plugin-astro
${imports.join("\n")}

export function init() {
  if (typeof window === "undefined") return;
${calls.join("\n")}
}

if (typeof window !== "undefined") {
  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", () => init());
  } else {
    init();
  }
}

export default { init };
`;
}
