name = "hyacine-api"
main = "src/index.ts"
compatibility_date = "2026-08-24"

[[d1_databases]]
binding = "DB"
database_name = "hyacine"
database_id = "local"

[[kv_namespaces]]
binding = "CACHE"
id = "local"

[[r2_buckets]]
binding = "ASSETS"
bucket_name = "hyacine-assets"

[ai]
binding = "AI"
